#!/usr/bin/env Rscript

################################################################################
## primer_blast_mismatch_plots_v1.R
################################################################################
## Description: Generate 3 x 3 primer pair mismatch frequency plots
##==============================================================================
## Author: A. Evans 24/02/2017
## R version 3.3.2 (2016-10-31)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: OS X El Capitan 10.11.6
## locale: en_GB.UTF-8
##------------------------------------------------------------------------------
##==============================================================================
## OPTIONS
##==============================================================================
## -i  --input       input csv file
## -o  --outfile     Output filename [default: primer_blast_outputs.csv]
## -h  --help        Display options
## -v  --verbose     Display all commands used to output device [default: FALSE]
##
## NOTE: Existing output file will be overwritten
##
##==============================================================================
## Input
##==============================================================================
## Takes primer_blast_v1.R output csv file [24 col by x rows]
## generated by study research criteria [9 x sources]
##
## Reads in:
##      col 3  Header: Source
##      col 13 Header: species
##      col 15 Header: mismatches_forward
##      col 16 Header: mismatches_reverse
##
##==============================================================================
## Output
##==============================================================================
## 3 x 3 bar plots: .pdf, .tiff and .eps
## mismatch frequency by source table:.txt
##==============================================================================

## library check and load

deps <- c("optparse")

missingdeps <- deps[!(deps %in% installed.packages()[ ,"Package"])]

if(length(missingdeps)) {
    missingdeps <- paste(missingdeps, collapse = "; ")
    stop(paste("Install packages:", missingdeps, sep = " "))
}


suppressPackageStartupMessages(library("optparse", quietly = TRUE))


## Parse command line arguments

option_list = list(
    make_option(c("-i", "--input"), type = "character", default = NULL, 
        help = "name of input csv file", metavar = "character"),
    make_option(c("-o", "--output"), type = "character", default = "primer_blast_mismatches", 
        help = "output file name [default =  %default]", metavar = "character"),
    make_option(c("-v", "--verbose"), action = "store", default = FALSE, 
        help = "Print extra output FALSE [default]")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

infl <- opt$input
outfl <- opt$output
verbose <- opt$verbose

options(echo = verbose)



## If input file exists, build data frame of mismatches

if (is.null(infl)){
    print_help(opt_parser)
    print("Supply input csv file name [Rscript primer_blast_mismatch_plots_v1.R -i filename]")
    opt <- options(show.error.messages = FALSE)
    on.exit(options(opt))
    stop()
} else if (!file.exists(infl)) {
    msg <- paste("File does not exist: ", infl, sep = "")
    stop(msg)
} else {
    print("Script called with the following:")
    optdf<-utils::str(opt, no.list = TRUE)
    print(optdf)

    ## append extensions for output

    outfl_tiff <- paste(outfl, ".tiff", sep = "")
    outfl_eps <- paste(outfl, ".eps", sep = "")
    outfl_pdf <- paste(outfl, ".pdf", sep = "")
    outfl_txt <- paste(outfl, ".txt", sep = "")

    ## Read in four cols only

hdr <- read.csv(file = infl, nrows = 1)
n_cols <- length(hdr)

vars <- rep("NULL", n_cols)
    vars[3]  <- "character"   # source
    vars[13] <- "character"   # species
    vars[15] <- "integer"     # mismatches_forward
    vars[16] <- "integer"     # mismatches_reverse

    cc = vars

    pbdf <- read.csv(infl, header = TRUE, sep = ",", na.strings = "", colClasses = cc)
}


## Summarize mismatch counts

pbdf$tot_mismatches <- rowSums(pbdf[ ,3:4])

mismatch_tbl <- with(pbdf, table(Source, tot_mismatches))


## Amend for plot headers

row.names(mismatch_tbl) <- gsub("Caporaso", "Caporaso et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Fierer", "Fierer et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Heuer", "Heuer et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("HMP", "HMP", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Maeda", "Maeda et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Muyzer", "Muyzer et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Schwieger", "Schwieger \\& Tebbe", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Shakya", "Shakya et al", row.names(mismatch_tbl))
row.names(mismatch_tbl) <- gsub("Weisburg", "Weisburg et al", row.names(mismatch_tbl))


devices <- c("pdf", "cairo_ps", "tiff")

for (i in seq_along(devices)) {

    if (devices[i] == "pdf") {
        pdf(outfl_pdf)
    } else if (devices[i] == "cairo_ps") {
        cairo_ps(file = outfl_eps)
    } else if (devices[i] == "tiff") {
        tiff(file = outfl_tiff, res = 600, family = "Arial", width = 190, height = 160, units = "mm")
    }

    ## generate 3 x 3 plots

    par(mfrow = c(3, 3), mar = c(2.8, 2.6, 2.5, 1.0))

    for (i in 1:9) {
        mlabel <- row.names(mismatch_tbl)[i]
        ylimits <- range(pretty(c(0, mismatch_tbl[i, ])))
        xlabel <- "Number of mismatches"
        ylabel <- "Frequency"
        cols <- c("black", "white")[(mismatch_tbl[i, ] < 1) + 1]

        mismatch_plot<- barplot(mismatch_tbl[i, ],  main = mlabel, yaxs = "r", 
                                ylim = ylimits, xlab = xlabel, ylab = ylabel, 
                                las = 1, col = cols, border = cols, ps = 7, 
                                cex.main = 1, cex.lab = 1, cex.axis = 0.86, 
                                cex.names = 0.86, tck = -0.025,  mgp=c(1.5, .3, 0))

        axis(1, at = mismatch_plot, labels = FALSE, tick = TRUE, ps = 7,  tck = -0.025)

        box(lwd = 0.8)
}

    graphics.off()

}


## output frequency table
write.ftable(ftable(mismatch_tbl), file = outfl_txt, sep = "\t", quote = FALSE)

